name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - backend/**
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: build and deploy frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: 16
      - name: build frontend
        run: |
          npm install
          npm run build --omit=dev
          rm -rf ../backend/build
          cp -r build ../backend/build
        working-directory: ./frontend
      - name: deploy app
        working-directory: ./backend
        run: flyctl deploy --remote-only